[package]
name = "flappy-ferris"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9.1"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable a high amount of optimization for dependencies
[profile.dev.package."*"]
opt-level = 3
